// app/layout.tsx or app/layout.js
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  nonce, // Asegúrate de pasar el nonce desde el middleware
}: {
  children: React.ReactNode;
  nonce?: string; // Añadir el nonce como un prop opcional
}) {
  return (
    <html lang="en">
      <head>
        {/* Ejemplo de cómo agregar el nonce a los estilos en línea si fuera necesario */}
        <style nonce={nonce}>{`
          body {
            background-color: #f0f0f0;
          }
        `}</style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        nonce={nonce} // Añade el nonce al body si hay scripts en línea o event handlers
      >
        {children}
      </body>
    </html>
  );
}
